# Generated by Django 4.2.10 on 2024-04-25 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.TextField(verbose_name='Тест')),
                ('time_limit', models.DecimalField(decimal_places=2, default=10, max_digits=6, null=True, verbose_name='Время')),
                ('pass_score', models.DecimalField(decimal_places=2, default=5, max_digits=6, null=True, verbose_name='Пороговый балл')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Текст вопроса')),
                ('point', models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Количество баллов за вопрос')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.test', verbose_name='Тест')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False, verbose_name='Правильный ответ?')),
                ('answer', models.TextField(verbose_name='Текст ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='profiles.question', verbose_name='Вопрос')),
            ],
        ),
    ]
