# Generated by Django 4.2.10 on 2024-05-16 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passed_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uuid', models.UUIDField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.question')),
            ],
        ),
    ]
