# Generated by Django 4.2.10 on 2024-05-17 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_passed_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='passed_question',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='passed_question',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.answer'),
        ),
    ]
