# Generated by Django 4.2.10 on 2024-06-05 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_passed_question_date_alter_passed_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret_Santa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_uuid', models.UUIDField()),
                ('name', models.TextField(verbose_name='Имя игрока')),
                ('type_link', models.TextField(verbose_name='Тип ссылки')),
                ('link', models.TextField(verbose_name='Ссылка игрока')),
                ('wish_list', models.TextField(null=True, verbose_name='Пожелания')),
                ('limit', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Ограничение на стоимость')),
                ('santa_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.secret_santa')),
            ],
        ),
    ]
